name: Validate Push

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'

jobs:
  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type checking
        run: npm run type-check

      - name: ESLint validation
        run: npm run lint:check

      - name: Prettier formatting check
        run: npm run prettier:check

      - name: Run tests (when implemented)
        run: npm test || echo "No tests yet"
        continue-on-error: true

      - name: Build project (when build exists)
        run: npm run build || echo "No build script yet"
        continue-on-error: true

  notify:
    name: Notify Status
    runs-on: ubuntu-latest
    needs: quality-gates
    if: always()

    steps:
      - name: Check result
        run: |
          if [ "${{ needs.quality-gates.result }}" == "success" ]; then
            echo "✅ Push validation passed!"
          else
            echo "❌ Push validation failed!"
            exit 1
          fi
